### ISSUE TITLE
自定义输出路径，无法添加logo到二维码中

### ISSUE THREAD

**Issue by shiqstone** [cinaofdai/think-qrcode#1]
使用自定义图片路径生成二维码之后
$code->png($url, $code_path, 4);

由于在logo，background，text方法中，都为outfile重新赋值，导致生成两个不同的图片文件，自定义路径对应的文件只是原始二维码

line 129：
public function logo($logo){
    ...
    $this->outfile = $this->cache_dir.'/'.time().'.png';
    ...
}

line 160:
public function background($x=200,$y=500,$dst_path = ''){
    ...
    $this->outfile = $this->cache_dir.'/'.time().'.png';
    ...
}

line 220:
public function text($text,$size,$locate =[],$color = '#00000000',$font='simsun.ttc', $offset = 0, $angle = 0) {
    ...
    $this->outfile = $this->cache_dir.'/'.time().'.png';
    ...
}

**Comment by cinaofdai** [comment]
这个不是这个问题。是修复的bug方式不对。最近会重新整理这个bug
